### PR TITLE
Fix relative import for Python 3

### PR DESCRIPTION
**Pull request by SpotlightKid**
(and order imports)

### CODE REVIEW

**Comment by velolala** [comment]
Hey @SpotlightKid!
So...tonight is [tonight](https://github.com/velolala/touchosc2midi/pull/6#issuecomment-151754814) it seems...

I tried to build it in python 3, but I could not get it to work, please see below. Do you expect it to build?

Here's what I did.

**edit**: I also needed to add `cython` to requirements, for the newest `pyliblo` to build.

```
cd touchosc2midi
docker run --rm -v $PWD:/data -it --entrypoint /bin/bash python:3.3.6  # or 3.4.3
apt-get update && apt-get install -y liblo-dev librtmidi-dev
cd /data && python setup.py install
```

this fails with:

```
Processing netifaces-0.10.4.tar.gz
...
  File "/tmp/easy_install-mnruk57p/netifaces-0.10.4/setup.py", line 17, in <module>
    packages=["touchosc2midi"],
AttributeError: 'dict' object has no attribute 'print'
```

This, may be a known issue: https://github.com/GNS3/gns3-server/issues/97 -- can you have a look?

**Comment by SpotlightKid** [comment]
Yes, the `setup.py` file of the `netifaces` package (which is a dependency of `zeroconf`) is broken for Python 3. AFAICS, this has nothing to with my PR, though. It "just" means that the dependencies of your project are apparently broken.

**Comment by SpotlightKid** [comment]
There's nothing much you can do about but pressure the `netiface` maintainers to release a fixed package or the `zeroconf` maintainers to switch their dependency to https://pypi.python.org/pypi/gns3-netifaces and also release a new version.

**Comment by SpotlightKid** [comment]
To be able to test your package under Python 3, you have to clone the [zeroconf repo](https://github.com/jstasiak/python-zeroconf), change the dependency in its `setup.py` from `netifaces` to `gns3-netiface`, install `zeroconf` from your clone in your virtualenv with `python setup.py install` and then proceed to install `touchosc2midi`.

**Pull request merged**
