### PR TITLE
Add support for sysex mesages

### PR DESCRIPTION
**Pull request by SpotlightKid**
Implements sysex part of issue #1.

### CODE REVIEW

**Comment by velolala** [comment]
Hey @SpotlightKid this looks great!
I'll try to have a thorough look and hopefully merge tonight.

**Comment by SpotlightKid** [comment]
Please note that I also included a fix in the try/except block in the main function, which prevents a NameError in the except clause when the program is interrupted with Control-C before the OSC server is created. Sorry that should normally have been a different PR but somehow slipped through.

**Comment by velolala** [comment]
Heya @SpotlightKid please see the comments for #5 

Also, I build this PR with py 2.7.9 and while it did indeed build and start/connect, I get spammed with

```
...
Exception TypeError: TypeError('<functools.partial object at 0x7f65bf3a74c8> is not a Python function',) in 'liblo._msg_callback' ignored
Exception TypeError: TypeError('<functools.partial object at 0x7f65bf3a74c8> is not a Python function',) in 'liblo._msg_callback' ignored
...
```

when receiving /midi from touchosc. Could you check that?
It would be awesome to have sysex!

**Comment by SpotlightKid** [comment]
This seems to be a bug in `pyliblo`. From its [documentation](http://dsacre.github.io/pyliblo/doc/) (my emphasis):

> add_method(path, typespec, func, user_data=None)
> 
> func – the callback function. This may be a global function, a class method, or _any other callable object_,
> pyliblo will know what to do either way.

It works in Python3, but not Python 2. I've opened a [pyliblo issue](https://github.com/dsacre/pyliblo/issues/12).

In the meantime, I can go back to your original method with a wrapped function or - which I prefer - a handler class. Updating the PR now.

**Comment by SpotlightKid** [comment]
Have you tried running the branch after my latest changes to the PR? Do you need any more input on this?

**Comment by h3xl3r** [comment]
I am wondering... why was this never merged?

**Comment by velolala** [comment]
> why was this never merged?

blame on me :blush: -- mainly lack of testing environment/specs and attention/time. This plus the python 2/3 difficulties (see #5 ).

Now that I see some (very welcome) traction for the project, I promise to look at it again.

**Comment by h3xl3r** [comment]
Python difficulties eh? I've heard about this before, but again, no experience with it. I'll install and try to integrate it into my regular testing setup, so maybe that way I can catch some problems.

**Comment by SpotlightKid** [comment]
If the project revives and accepts PRs again, I have a few more improvements lined up:

https://github.com/SpotlightKid/touchosc2midi/commits/feature/generickeys

**Comment by velolala** [comment]
I'm terribly sorry @SpotlightKid ! I did not show enough appreciation for all your efforts (software- as well as outreach-wise).

**Comment by SpotlightKid** [comment]
No worries, I needed the features for my own setup, so I went ahead and implemented them. If there's something useful for you in there, let me know.

**Comment by velolala** [comment]
hmm. no idea how exactly I ended up here, but I got your PR merged, just not in a way that github acknowledges.
Thank you very much for your contributions @SpotlightKid ! I'll give it a couple of tests and will try to create a new release soon!

**Pull request closed without merging**
